# Generated by Django 4.1.7 on 2023-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_pub_date_product_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Compare_with_new_at',
            field=models.URLField(blank=True, null=True),
        ),
    ]
