# Generated by Django 4.1.7 on 2023-04-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_compare_with_new_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Compare_with_new_at',
            new_name='url',
        ),
    ]
