# Generated by Django 4.1.7 on 2023-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_compare_with_new_at_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
