# Generated by Django 4.1.7 on 2023-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Product_Selected',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
