# Generated by Django 4.1.7 on 2023-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_customer_product_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Product_Selected',
            field=models.CharField(max_length=100),
        ),
    ]
