# Generated by Django 4.1.7 on 2023-04-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_customer_product_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact_Number',
            field=models.CharField(max_length=10),
        ),
    ]
