# Generated by Django 4.1.7 on 2023-04-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_customer_contact_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('Contact_Number', 'Product_Selected')},
        ),
    ]
