# Generated by Django 4.1.7 on 2023-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_customer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Product_Selected', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='', upload_to='shop/sellenquiryimages')),
                ('purchase_date', models.DateField()),
                ('Brand', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('Contact_Number', 'Product_Selected')},
            },
        ),
    ]
