# Generated by Django 4.1.7 on 2023-04-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_sellenquiry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellenquiry',
            old_name='Brand',
            new_name='Brand_name',
        ),
    ]
