# Generated by Django 4.1.7 on 2023-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_rename_brand_sellenquiry_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='shop/sellenquiryimages'),
        ),
    ]
