# Generated by Django 4.1.7 on 2023-04-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_sellenquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='image',
            field=models.FileField(upload_to='shop/sellenquiryimages'),
        ),
    ]
