# Generated by Django 4.1.7 on 2023-04-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_sellenquiry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellenquiry',
            name='image',
        ),
    ]
