# Generated by Django 4.1.7 on 2023-04-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_remove_sellenquiry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellenquiry',
            name='image1',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='image2',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='image3',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
    ]
