# Generated by Django 4.1.7 on 2023-04-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_sellenquiry_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellenquiry',
            unique_together={('Contact_Number', 'Product_Selected')},
        ),
    ]
