# Generated by Django 4.1.7 on 2023-04-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_sellenquiry_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellenquiry',
            old_name='product_image1',
            new_name='product_Back_Image',
        ),
        migrations.RenameField(
            model_name='sellenquiry',
            old_name='product_image2',
            new_name='product_Front_Image',
        ),
        migrations.RenameField(
            model_name='sellenquiry',
            old_name='product_image3',
            new_name='product_Side_Image',
        ),
    ]
