# Generated by Django 4.1.7 on 2023-04-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_sellenquiry_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellenquiry',
            name='dropdown_field',
        ),
    ]
