# Generated by Django 4.1.7 on 2023-04-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_sellenquiry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellenquiry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='dropdown_field',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.RemoveField(
            model_name='sellenquiry',
            name='Product_Selected',
        ),
    ]
