# Generated by Django 4.1.7 on 2023-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_sellenquiry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='dropdown_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
