# Generated by Django 4.1.7 on 2023-04-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_sellenquiry_dropdown_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellenquiry',
            unique_together={('Contact_Number', 'product')},
        ),
    ]
