# Generated by Django 4.1.7 on 2023-04-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_sellenquiry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product'),
        ),
    ]
