# Generated by Django 4.1.7 on 2023-04-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_rename_product_bill_or_invoice_sellenquiry_product_bill_or_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.allproductnames'),
        ),
    ]
