# Generated by Django 4.1.7 on 2023-04-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('shop', '0058_userprofile_email_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
            ],
            bases=('socialaccount.socialaccount',),
        ),
    ]
