# Generated by Django 4.1.7 on 2023-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_customsocialaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSocialAccount',
        ),
    ]
