# Generated by Django 4.1.7 on 2023-04-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_remove_userprofile_full_name_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
