# Generated by Django 4.1.7 on 2023-04-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_sellenquiry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellenquiry',
            name='user',
        ),
    ]
