# Generated by Django 4.1.7 on 2023-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_remove_sellenquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellenquiry',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
