# Generated by Django 4.1.7 on 2023-05-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
