# Generated by Django 4.1.7 on 2023-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellenquiry',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
