# Generated by Django 4.1.7 on 2023-05-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_sellenquiry_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='PurchaseEnquiry',
        ),
    ]
