# Generated by Django 4.1.7 on 2023-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_purchaseenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseenquiry',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
