# Generated by Django 4.1.7 on 2023-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_purchaseenquiry_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='Status',
            field=models.CharField(default='Status: under review', max_length=20),
        ),
    ]
