# Generated by Django 4.1.7 on 2023-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_alter_sellenquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseenquiry',
            name='Product_Selected',
            field=models.CharField(default='', max_length=200),
        ),
    ]
