# Generated by Django 4.1.7 on 2023-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_alter_purchaseenquiry_product_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseenquiry',
            name='Status',
            field=models.CharField(default='Status: under review', max_length=20),
        ),
    ]
