# Generated by Django 4.1.7 on 2023-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_alter_purchaseenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backimage',
            field=models.ImageField(blank=True, default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='sideimage',
            field=models.ImageField(blank=True, default='', upload_to='shop/images'),
        ),
    ]
