# Generated by Django 4.1.7 on 2023-05-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_product_backimage_product_sideimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WAIST', 'Waist'), ('LENGTH', 'Length'), ('ALTERED', 'Is Altered'), ('CHEST', 'Chest')], max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('is_altered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.clothingsize'),
        ),
    ]
