# Generated by Django 4.1.7 on 2023-05-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_alter_clothingsize_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingsize',
            name='category',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('Is Altered', 'Is Altered')], max_length=10),
        ),
    ]
