# Generated by Django 4.1.7 on 2023-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_remove_clothingsize_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellenquiry',
            name='chest',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='is_altered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='length',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellenquiry',
            name='waist',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ClothingSize',
        ),
    ]
