# Generated by Django 4.1.7 on 2023-05-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_sellenquiry_chest_sellenquiry_is_altered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellenquiry',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='sellenquiry',
            name='is_altered',
        ),
        migrations.RemoveField(
            model_name='sellenquiry',
            name='length',
        ),
        migrations.RemoveField(
            model_name='sellenquiry',
            name='waist',
        ),
    ]
