# Generated by Django 4.1.7 on 2023-05-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_alter_sellenquiry_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
