# Generated by Django 4.1.7 on 2023-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_delete_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backimage',
            field=models.ImageField(blank=True, default='Image coming soon', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sideimage',
            field=models.ImageField(blank=True, default='Image coming soon', upload_to='shop/images'),
        ),
    ]
