# Generated by Django 4.1.7 on 2023-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_alter_product_backimage_alter_product_sideimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Back_Image',
            field=models.ImageField(blank=True, default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Bill_or_Invoice',
            field=models.FileField(blank=True, default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Front_Image',
            field=models.ImageField(blank=True, default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Side_Image',
            field=models.ImageField(blank=True, default='', upload_to='shop/sellenquiryimages'),
        ),
    ]
