# Generated by Django 4.1.7 on 2023-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_alter_sellenquiry_product_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Back_Image',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Front_Image',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
        migrations.AlterField(
            model_name='sellenquiry',
            name='product_Side_Image',
            field=models.ImageField(default='', upload_to='shop/sellenquiryimages'),
        ),
    ]
